[tool.poetry]
name = "xinstall"
version = "0.3.4"
description = ""
authors = ["Benjamin Du <longendu@yahoo.com>"]

[tool.poetry.scripts]
xinstall = 'xinstall:main.main'

[tool.poetry.dependencies]
python = ">=3.6"

[tool.poetry.dev-dependencies]
pytest = ">=3.0"
pylint = "^2.4.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
